"use client";

import { Amplify } from "aws-amplify";
import outputs from "../amplify_outputs.json";

let configured = false;

// Point the Amplify libraries at our deployed backend (Cognito + AppSync). The
// outputs file is generated by `npx ampx sandbox` locally and by the Amplify
// build in the cloud — it's never committed.
export function configureAmplify() {
  if (configured) return;
  Amplify.configure(outputs, { ssr: true });
  configured = true;
}
